### ISSUE TITLE
XP下，进入Shadowsocks那个 文件夹，启动不了，提示出错

### ISSUE THREAD

**Issue by skybai1987** [yeahwu/firefox-tor#3]

**Comment by yeahwu** [comment]
你有没有ss帐号？没有的话用前置lantern。这个应该不可能吧？官方的shadowsocks包。

**Comment by skybai1987** [comment]
@yeahwu ss帐号要怎么弄的。感觉用lantern，搜索都有点慢。那个打不开，是因为xp的原因，win7提示要安装net.frame啥的
